import ThemeProvider from "@/contexts/ThemeProvider";
import AuthProvider from "@contexts/auth/AuthProvider";
import '@styles/giohang.css';
// import '@styles/gioithieu.css';
import "@styles/globals.css";
import '@styles/responsive.css';
import { Inter } from 'next/font/google';
import Footer from "./ui/RootLayout/Footer";
import Header from "./ui/RootLayout/Header";

export const metadata = {
  title: "Jewelry Website",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ThemeProvider>
          <AuthProvider>
            <main>
              <Header />
              {children}
              <Footer />
            </main>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
