import ThemeProvider from "@/contexts/ThemeProvider";
import '@styles/giohang.css';
import "@styles/globals.css";
import '@styles/responsive.css';
import { Inter } from 'next/font/google';
import Header from "./ui/RootLayout/Header";

export const metadata = {
  title: "Jewelry Website",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {/* <SessionProvider> */}
        <ThemeProvider>
          {/* <AuthProvider> */}
          <main>
            <Header />
            {children}
          </main>
          {/* </AuthProvider> */}
        </ThemeProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
